coursework:
	cl find.c
	find hello -i input.txt -o output.txt
	find hello -c
	find duchess -i input2.txt -o output2.txt -c
	find sullen -i input3.txt -o output3.txt -c
	find homeward -i input4.txt -o output4.txt -c